### ISSUE TITLE
Load local resources

### ISSUE THREAD

**Issue by PatrikTes** [salvadordf/CEF4Delphi#109]
Hello I was using previous version and I was able to load the images and css styles relatively to my EXE file. Scenario as follows : 

- Images and css are stored localy
- Load empty HTML with LoadURL and set to same path DefaultURL
- I generate the HTML string and load it to browser

This scenario was working on CEF3, now it is not :(

anybody can help?

**Comment by PatrikTes** [comment]
Additional information : in LoadString I'm correctly using the second parameter with "file:///" and the path to the local file on the path where are the resources.

Any help would be great :(

**Comment by salvadordf** [comment]
To load local resources you can use a custom scheme handler or you can set GlobalCEFApp.DisableWebSecurity to TRUE.

Take a look at the SchemeRegistrationBrowser demo for more info about the first solution.

**Comment by salvadordf** [comment]
Use the SchemeRegistrationBrowser demo as a base for your app if you still have problems opening local resources.

https://github.com/salvadordf/CEF4Delphi/tree/master/demos/SchemeRegistrationBrowser

**Comment by dandiaalar** [comment]
Hello,
I have a project in which I want to display google map and perform some functions like adding markers and drawing routes.
Using the SimpleBrowser2 demo along with an html file the application works fine (the map is displayed and the javascript functions I call are executed). However, I need to do something like the CustomResourceBrowser demo in which, in the FormCreate, declare a
TempStream := TStringStream.Create('<!DOCTYPE html><html><body><p>TEST</p></body></html>', TEncoding.UTF8, false);

The CustomResourceBrowser demo does show the text "TEST" of the inserted html code but, when modifying and inserting only the map load, it shows an error message indicating "google is not defined".

If I take that html code and paste it into a file and open it in a browser, the map is displayed.

I require the CustomResourceBrowser to not depend on the independent html file so that it cannot be modified or deleted.

I don't know if it is possible to occupy the google map with this implementation?

**Comment by salvadordf** [comment]
Hi,

The SchemeRegistrationBrowser demo reads some contents from a local file into a stream but it should be possible to load a simple string into that stream too. That demo has a simple Google Maps example that needs an API key to work.

Register the "http" or "https" schemes instead of registering the "hello" scheme to avoid some issues.

Please, use [our forum](https://www.briskbard.com/forum/) for more questions.

**Comment by dandiaalar** [comment]
Hi Salvador,

First of all, I must mention that I am new to the topic of development with Delphi.

I took the example you mentioned (SchemeRegistrationBrowser) and loaded the html code in a string, registered the "https" scheme but the result is the same, the map is not displayed. Again, if I right click on the window, view the page code, copy it to a separate file and open it in a browser, the map does display.

By the way, I already registered in the forum but I haven't received the message to confirm my account.

**Comment by salvadordf** [comment]
Please, let me know the username in the forum to activate the account manually.

**Comment by dandiaalar** [comment]
the user name is dandiaalar.

Thank's

**Comment by salvadordf** [comment]
The account has been activated. Sorry!
