### ISSUE TITLE
CefRenderProcessHandler not found.

### ISSUE THREAD

**Issue by joaofrassetto** [salvadordf/CEF4Delphi#136]
I'm migrating from dcef3 to dcef4, but get stuck at this point: 

`initialization
  CefRenderProcessHandler := TCustomRenderProcessHandler.Create();`

I don't know how to proceed now.

**Comment by salvadordf** [comment]
CEF4Delphi creates CefRenderProcessHandler, CefBrowserProcessHandler and CefResourceBundleHandler automatically only if they are needed.

All the events in CefRenderProcessHandler, CefBrowserProcessHandler and CefResourceBundleHandler are now available in GlobalCEFApp.

For example, if you used TCefCustomRenderProcessHandler.OnWebKitInitialized in your DCEF3 app now you only need to use the GlobalCEFApp.OnWebKitInitialized event in CEF4Delphi.

You don't need to create any process handlers because CEF4Delphi do that for you internally.

If you have more questions, don't hesitate to use our forum at https://www.briskbard.com/forum/
