### ISSUE TITLE
MiniBrowser demo when mouse click links then it will show a form

### ISSUE THREAD

**Issue by hakwolf** [salvadordf/CEF4Delphi#140]
i spend a lot of time to find the code what when mouse click links then it  will show a form,but i gained nothing.can  you tell me where it is?think you.

**Comment by salvadordf** [comment]
Most of the demos block all new tabs and popup windows to keep the code as simple as possible but MiniBrowser is the only demo that allows CEF3 to create the popup windows automatically. 

The PopupBrowser and PopupBrowser2 demos also create popup windows but they use Delphi forms, while MiniBrowser lets CEF3 create the new windows internally. 

The **TChromium.OnBeforePopup** event is used to block or allow new tabs and popup windows. Setting the "_Result_" parameter to TRUE will block the new window but the default value for "_Result_" is FALSE. 

The MiniBrowser demo doesn't use the TChromium.OnBeforePopup event, so all new windows are allowed. However, you will see code like the following in many other events : 
`if not(Chromium1.IsSameBrowser(browser)) then exit;`

When you allow CEF3 to create new windows, all the browsers will use the same code for the events. For example, if the web page title changes in the new popup window it will trigger the TChromium.OnTitleChange event in the main form. That's why some events check what browser is triggering that event and they exit if it's not the same browser.

If you have more questions, please use our forums at : 
https://www.briskbard.com/forum/
