### ISSUE TITLE
flash problem

### ISSUE THREAD

**Issue by hakwolf** [salvadordf/CEF4Delphi#144]
when i use   GlobalCEFApp.CustomFlashPath:= '.\PepperFlash',some website can play mormal but  popup a black box. How ever , one website what url is 'http://www.iqiyi.com/' ,   it is a  video website,    the special pearl case is black screen.Did you find that?why google chrom Browser use this plugn to run normal,But our CEF Can not?

**Comment by salvadordf** [comment]
The black box is a CMD prompt created by the Adobe Flash plugin. It's a known bug in that plugin but we have 2 ways to avoid it : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=620
https://www.briskbard.com/forum/viewtopic.php?f=8&t=137&p=714&hilit=detours#p714

If you have problems with some video websites it might be caused by the use of proprietary video codecs. The CEF3 binaries used by CEF4Delphi only have the open source codecs enabled to avoid legal problems. If you need the proprietary codecs you can enable them by building the CEF3 binaries with some modifications. Read this forum thread : 
http://magpcss.org/ceforum/viewtopic.php?f=6&t=13515

Chrome doesn't use CEF3. CEF 3 is a multi-process implementation based on the Chromium Content API. Read this article for more information : 
https://en.wikipedia.org/wiki/Chromium_Embedded_Framework

Please, use our forums for more questions :
https://www.briskbard.com/forum/

If you have any problem activating the forum account send me a message with your account name and I'll activate it manually.

**Comment by hakwolf** [comment]
If you have problems with some video websites it might be caused by the use of proprietary video codecs. 
i find it is't that  reason. this mfc demo in release dir of  https://github.com/xiaonaiquan/CEF3.open it demo exe,it can open it one video can normal play.And it can not open proprietary video codecs. Is it the problem of flash?
