### ISSUE TITLE
open in new window problem

### ISSUE THREAD

**Issue by hakwolf** [salvadordf/CEF4Delphi#147]
Chromium1BeforePopup ,in this event , i can use parameters:targeturl to process most links,but i find  value of  some links is null.so my code can't open url in new tabsheet.I researh your popup Broswser demos,your code can open the new window form even the value of  targeturl is null.my target is Integrating new window form  into Newly Created tabsheet  Controls.So i can only use your demo code to do?I’ve tried your code to my project ,but i found  when i cose this new page,release the new tabsheet ,it will show a error.I try to build a browser similar to chrome,can you give me some suggestions.

**Comment by salvadordf** [comment]
Read this forum post : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=99&p=1722&hilit=popupbrowser2#p1719

Opening new popup windows or new tabs is complicated because TChromium.OnBeforePopup is executed in a different thread and you should create and destroy VCL components in the main thread only. 

Use the code in the **PopupBrowser2** demo : 
https://github.com/salvadordf/CEF4Delphi/tree/master/demos/PopupBrowser2

...and please, stop creating issues for questions. I'll be glad to help you in our forum : 
https://www.briskbard.com/forum/

If you have any problem accessing our forum just let me know.
