### ISSUE TITLE
 cef4delphi 中的 js与delphi的相互调用样例没有啊? 我在delphi7中测试JSwindowBinding无法正常编译

### ISSUE THREAD

**Issue by miws** [salvadordf/CEF4Delphi#152]
cef4delphi 中的 js与delphi的相互调用样例没有啊? 我在delphi7中测试JSwindowBinding无法正常编译
`GlobalCEFApp.OnContextCreated := GlobalCEFApp_OnContextCreated;`

这一句提示不兼容
Incompatible types: 'method pointer and regular procedure'

**Comment by salvadordf** [comment]
I'm sorry but I only understand Spanish, English and some Italian. 

I used an online translator and I think you may fix that problem by converting the GlobalCEFApp_OnContextCreated procedure to a public TJSSimpleWindowBindingFrm procedure.

Then you would only have to modify the assignment : 
GlobalCEFApp.OnContextCreated := JSSimpleWindowBindingFrm.GlobalCEFApp_OnContextCreated;

I don't have a Delphi 7 license and I can't test this but you may also have problems with the IMAGE_FILE_LARGE_ADDRESS_AWARE constant in the DPR file. The SimpleBrowser demo for Delphi 7 uses $20 instead of that constant.

Please, consider downloading Delphi 10.3 Community Edition. It's free and all the CEF4Delphi demos run without modifications in that version.
https://www.embarcadero.com/products/delphi/starter/free-download
