### ISSUE TITLE
Slowly MS Excel startup while a web browser used 'dxGDIPlusClasses' unit is running

### ISSUE THREAD

**Issue by lanxuanchen** [salvadordf/CEF4Delphi#158]
Hi, I have a problem and I don't know how to solve it. 

I use MDIBrowser Demo to test and add 'ExpressGDI+ Library' unit 'dxGDIPlusClasses' in uses.

If there is a TChromium running in MDIBrowser Demo and you try to open a xlsx file or a word file from the explorer, it will take up long time to start.

When you close the TChromium browser, Excel or word will start almost instantly or
when you remove 'dxGDIPlusClasses' unit from uses and run MDIBrowser Demo, Excel or word also will start almost instantly.

Tested with :

Delphi 10.2

Microsoft Office Standard 2007 and Microsoft Office Standard 2016

Windows 7 PRO (64-Bit ver 6.1.7601)

**Comment by lanxuanchen** [comment]
The unit 'dxGDIPlusClasses' is included in DevExpressVCL. 
if you use unit 'dxShadowWindow' in MDIBrowser Demo, the same phenomenon will happen too with used 'dxGDIPlusClasses' unit.

**Comment by salvadordf** [comment]
The cause of this problem is explained in the issue #139 
https://github.com/salvadordf/CEF4Delphi/issues/139

I don't know DevExpressVCL but it's probably creating a "window" (using the Windows API term) and Excel is waiting for an answer to WM_DDE_INITIATE from all processes with a "window".

Chromium uses several processes and only the browser process can process WM_DDE_INITIATE, the rest of processes are busy and they can't process WM_DDE_INITIATE. This is the cause of the startup delay.

The easiest solution is to use a different EXE for the CEF subprocesses. The "SubProcess" demo shows you how to do it.
