### ISSUE TITLE
Intercept upload box?

### ISSUE THREAD

**Issue by radiaku** [salvadordf/CEF4Delphi#161]
hello, I'am new in freepascal and delphi ( c# programmer here ). Is there any ways to intercept or override upload file chooser ? I want to automate that , So I dont have to choose a file for each time. 

in c# I can do this

```
public class TempFileDialogHandler : IDialogHandler
    {
        string filepath_temp = @"C:\Users\root\Desktop\pascalbook\modern_pascal_introduction.pdf";
        public bool OnFileDialog(IWebBrowser browserControl, IBrowser browser, CefFileDialogMode mode, CefFileDialogFlags flags, string title, string defaultFilePath, List<string> acceptFilters, int selectedAcceptFilter, IFileDialogCallback callback)
        {
            callback.Continue(selectedAcceptFilter, new List<string> { filepath_temp });
            //callback.Continue(selectedAcceptFilter, new List<string> { Path.GetRandomFileName() });

            return true;
        }
    }
```

and then binding it , just like this
`browser.DialogHandler = new TempFileDialogHandler();`

is CEF4Delphi have same method? or Which function called when upload box show up? or any clue will be appreciate.

Thanks you, warm regards

**Comment by salvadordf** [comment]
Hi,

Yes, you can do that with CEF4Delphi but using "events".

As you can see in uCEFChromium.pas, TChromium has a bunch of events that have almost the same name as the handler methods you are used to work with. That's because TChromium creates the handlers in case you use one event that needs it.

For example, if you use the TChromium.OnFileDialog event then TChromium will create a IDialogHandler instance and IDialogHandler.OnFileDialog will trigger the TChromium.OnFileDialog event.

In this case all you need to do to override the file chooser is to use TChromium.OnFileDialog and call "callback.Continue" inside that event.

TChromium and TCefApplication hide all the complexities of creating and destroying handlers. 

TChromium has events for ICefClient, ICefLoadHandler, ICefFocusHandler, ICefContextMenuHandler, ICefKeyboardHandler, ICefDisplayHandler, ICefDownloadHandler, ICefJsDialogHandler, ICefLifeSpanHandler, ICefRequestHandler, ICefDialogHandler, ICefRenderHandler, ICefDragHandler and ICefFindHandler.

TCefApplication has events for ICefBrowserProcessHandler, ICefResourceBundleHandler, ICefRenderProcessHandler, ICefRegisterCDMCallback and ICefLoadHandler.

CEF4Delphi uses a multithreaded message loop by default. That means that all those events are triggered in CEF threads. 

As you know, you should modify the GUI components in the main thread only. Some demos ignore that to keep them as simple as possible but it's recommended that you save the event parameters and then send a message to the main form to update the GUI with that information.

Please read this for more CEF4Delphi information : 
https://www.briskbard.com/index.php?lang=en&pageid=cef

If you have more questions, please use our forum : 
https://www.briskbard.com/forum

**Comment by radiaku** [comment]
@salvadordf 

Thanks for explanation , I searching through  uCEFChromium.pas only this function that I found out. But I have no clue how to override this one

```
function TChromium.doOnFileDialog(const browser              : ICefBrowser;
                                        mode                 : TCefFileDialogMode;
                                  const title                : ustring;
                                  const defaultFilePath      : ustring;
                                  const acceptFilters        : TStrings;
                                        selectedAcceptFilter : Integer;
                                  const callback             : ICefFileDialogCallback): Boolean;
begin
  Result := False;

  if Assigned(FOnFileDialog) then
    FOnFileDialog(Self, browser, mode, title, defaultFilePath, acceptFilters,
                  selectedAcceptFilter, callback, Result);
end;  
```

If you have time, Can you give me some example, please? 

Thank you :)

**Comment by salvadordf** [comment]
Overriding that function is oneof the ways to do what you need but it's not the easiest way.
Usually, you would do this inside Lazarus : 

- Drop a "TChromium" component in a form.
- Go to the "Object inspector" and select the "Events" tab.
- Double click in the white space next to the "OnFileDialog" event and Lazarus will add an empty event to your form like this one : 
`procedure TChildForm.Chromium1FileDialog(Sender: TObject;
  const browser: ICefBrowser; mode: TCefFileDialogMode; const title,
  defaultFilePath: ustring; const acceptFilters: TStrings;
  selectedAcceptFilter: Integer; const callback: ICefFileDialogCallback; out
  Result: Boolean);
begin

end;`

- Then you add the code to that event. In this case you have to set "Result" to TRUE and call "callback.cont" : 
`procedure TChildForm.Chromium1FileDialog(Sender: TObject;
  const browser: ICefBrowser; mode: TCefFileDialogMode; const title,
  defaultFilePath: ustring; const acceptFilters: TStrings;
  selectedAcceptFilter: Integer; const callback: ICefFileDialogCallback; out
  Result: Boolean);
var
  TempPaths : TStringList;
begin
  Result := True;
  TempPaths := TStringList.Create;
  TempPaths.Add(defaultFilePath); // You probably need to convert defaultFilePath (UnicodeString) to String here.
  callback.cont(selectedAcceptFilter, TempPaths);
  TempPaths.Free;
end; `

Overriding a function is easy but then you would have to use the subclass in your form and that require extra steps.

**Comment by radiaku** [comment]
@salvadordf 

How dumb am I, I forgot about this is GUI developing and I can use it with Events ( like in visual studio ). For a moment, I forgot about everything, cause my thought about pascal is new language and different family from C. 

I have achieved more understanding about pascal and their visual GUI elements. Now I will learn about subclass, I know it wont easy cause not many eBook, tutorial and example in pascal. 

And many THANKS for enlightenment, Sifu.
