### ISSUE TITLE
Google Drive stopped listing files

### ISSUE THREAD

**Issue by amlynnworth** [salvadordf/CEF4Delphi#169]
Recently, the google drive page stopped working with my Delphi app that uses CEF4Delphi.  It had worked fine for more than a year.  Now the drive web page shows only the top header and left side menu, but zero folders nor files in the middle. 

The URL of Google Drive is https://drive.google.com/drive/my-drive

I just tried upgrading to the latest CEF4Delphi code with the latest win64 binaries. Problem remains. 
Tested on Windows 10 pro.

I am reporting this because it seems likely that CEF4Delphi needs to move to a newer version of Chromium.  Seems we are using 72 and there is a  Version 75.0.3732.0 available as of March 12 2019 (reference https://chromium.woolyss.com/download/en/ )

Thank you for maintaining this.  I find many uses for it.

**Comment by salvadordf** [comment]
At this moment, the latest stable version is 72.0.3626.121. 
The 73 version is expected to reach the stable channel today as you can see here : 
https://www.chromium.org/developers/calendar

This issue was discussed in the CEF3 project too because the official CEF3 application also has this problem with Google Drive : 
https://bitbucket.org/chromiumembedded/cef/issues/2588/branch-version-3683-does-not-support

As you can see in the last link, it seems that Google Drive is attempting to use a Chrome feature that is not supported by CEF3 (yet).

I tested the workaround given in that link and it works. Change the _user agent_ in your app by adding this before the GlobalCEFApp.StartMainProcess call in the DPR file : 
`GlobalCEFApp.UserAgent := 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0';`

**Comment by salvadordf** [comment]
I just noticed that I gave a user agent string for a Linux browser. Use the Windows version in your application.
