### ISSUE TITLE
MP4 play crashed application

### ISSUE THREAD

**Issue by shariful2011** [salvadordf/CEF4Delphi#197]
With reference to issue [https://github.com/salvadordf/CEF4Delphi/issues/76](url) and issue [https://github.com/salvadordf/CEF4Delphi/issues/21](url), as you mentioned in issue # 76 that MP4 will be enabled by default in the official libraries when Chromium 64 is released in Jan 23rd, 2018. But I tried with latest Cef4 with a crash on a loading of mp4 file. Below is my simple HTML file:

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>

<body>
	<video autoplay width="300" height="300">
		<source src="file:///F:/WORK/Freelancer/ProgramDelphi/cef4_mp4/Clip_1080_5sec_10mbps_h264.mp4" type="video/mp4">
	Your browser does not support the video tag.
	</video>
</body>
</html>

It crashed on loading without any error message

**Comment by salvadordf** [comment]
Sorry, I should have given a more detailed explanation about what is supported. 

At this moment you can play MP3 contents because the demuxer/decoder is no longer proprietary. 

However, only the MP4 (mov) demuxer is no longer proprietary. The H264 and AAC codecs still require a license because they are still proprietary.

Read this for more information about this issue :
https://bugs.chromium.org/p/chromium/issues/detail?id=746579

If you need to play multimedia contents using proprietary codecs you can build the CEF binaries following these instructions : 
https://www.briskbard.com/index.php?lang=en&pageid=cef#codecs

**Comment by shariful2011** [comment]
Please help me to build the CEF binaries. I downloaded [https://bitbucket.org/chromiumembedded/cef/src/master/](url). As per [https://magpcss.org/ceforum/viewtopic.php?f=6&t=13515](url) can't find cef.gypi. Also, you mentioned about the visual studio but can't find any visual studio solution file in the source file.

**Comment by salvadordf** [comment]
I'm sorry but I can't help you. I've never built the CEF binaries and my computer is not powerful enough to do it.

Please use the official CEF forum for questions about building CEF : 
https://magpcss.org/ceforum/
