### ISSUE TITLE
disable NetworkService problem

### ISSUE THREAD

**Issue by betafoxy** [salvadordf/CEF4Delphi#216]
when i disable NetworkService，will cause flash play "rtmp stream" blocked，test page：
[https://www.wowza.com/resources/3.6.0/examples/LiveVideoStreaming/FlashRTMPPlayer/player.html](url)

but：when i enable NetworkService，cause another problem：PersistSessionCookies not effect，my some site must login everytime；when disable ns notneed。。。

so，i am blocked//////

ps：i can't signup the dev forum。 O(∩_∩)O

**Comment by salvadordf** [comment]
The issue with the PersistSessionCookies setting was fixed in the CEF binaries since July 25th.
https://bitbucket.org/chromiumembedded/cef/commits/f84547cd340dcbd599845f752e2a6aba965469ea
Use the latest CEF4Delphi version and check that the windows user has write privileges in the cache directory. 

PS : Your user "betafox" is active in the forum. Use the option to recover a forgotten password.

**Comment by betafoxy** [comment]
lol, i use the CEF75.1.4+g4210896+chromium-75.0.3770.100, will update soon...

thanks//
