### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#245]
CEF4Delphi has most of the code needed to embed browsers in **Lazarus/FPC** applications on Linux but it's not complete.

We have reached the point where CEF4Delphi can be compiled under Linux but the demos crash when the browser is created.

**Comment by ahausladen** [comment]
If LCL's message loop is replaced by a call to GlobalCEFApp.RunMessageLoop and MultiThreadedMessageLoop is disabled then the browser appears and can be used. But that may have other side effects for the LCL. The LCL (gtk2) doesn't seem to be able to handle message queues in different threads (CheckSynchronize call from the UI Thread throws an exception because it wasn't called on the MainThread)

**Comment by pmamod** [comment]
First off all: Thanks a lot for your great job!
I'm using CEF4Delphi with Delphi and Lazarus on Windows and now I want to use it on Linux. My use case is OSR mode. I've made some changes to improve the support on Lazarus/Linux and attached the modified files. @salvadordf: If you want, please let the changes flow into the project. For more information feel free to contact me.
[CEF4Delphi-sourceModifiedByPMA.tar.gz](https://github.com/salvadordf/CEF4Delphi/files/3977008/CEF4Delphi-sourceModifiedByPMA.tar.gz)

**Comment by salvadordf** [comment]
Thank you very much! :D 

I just added your changes to the project and I also added a couple of Linux demos for Lazarus : SimpleBrowser2 and SimpleOSRBrowser.

They are incomplete and both of them crash. I'll create a new issue in GitHub for them.

Feel free to send pull requests and don't hesitate to use our forums if you need anything else : 
https://www.briskbard.com/forum/

**Comment by salvadordf** [comment]
The reason of the crashes has been identified and fixed in the SimpleOSRBrowser demo. Other demos will be fixed the same way.
