### ISSUE TITLE
SimpleFMXBrowser shows a blank screen when restored from the task bar

### ISSUE THREAD

**Issue by SoftacomDevelopment** [salvadordf/CEF4Delphi#253]
Installed FMXChromium, cef.dll v78.3.4, RAD Studio 10.3.2, Win10x64.
Demo App:
- SImpleFMXBrowser looks works well;
- FMXExternalPumpBrowser: 
    1) Build app/run
    2) Google.com page loaded
    3) After manual browser resize the app UI becames frozen and I able to close the app only from WIndows Task Manager
![image](https://user-images.githubusercontent.com/29306435/70705153-8c49f600-1ce4-11ea-940f-28a5b3f7f51b.png)

**Comment by SoftacomDevelopment** [comment]
SImpleFMXBrowser app has no any browser content on form after minimizing app window and restore it position back

**Comment by salvadordf** [comment]
Hi,

FMXExternalPumpBrowser use the OSR and that issue was fixed recently. Please, download the latest CEF4Delphi version.

I can reproduce the SimpleFMXBrowser issue. I'll try to fix it as soon as I can.

**Comment by SoftacomDevelopment** [comment]
Thanks for your reply

**Comment by salvadordf** [comment]
This bug was fixed with this commit : 
https://github.com/salvadordf/CEF4Delphi/commit/e53cc7ee5d6afc1e62b12ae76d71863dd5609fc5

Related forum thread : 
https://www.briskbard.com/forum/viewtopic.php?f=10&t=913

I implemented the workaround that Bandy gave in the forum when the window state changes. It was necessary to add a new property in the main form called CurrentWindowState to get the real window state and check when the form was restored.

**Comment by salvadordf** [comment]
The first fix for this issue was incomplete. In order to fix this it was necessary to replace the uFMXApplicationService unit with a custom WndProc procedure to handle the Windows messages correctly.

**Comment by chinacodegear** [comment]
when  will resolve the problem?

**Comment by salvadordf** [comment]
@chinacodegear : This bug was fixed on January 2nd with this commit :
https://github.com/salvadordf/CEF4Delphi/commit/e53cc7ee5d6afc1e62b12ae76d71863dd5609fc5

Please download CEF4Delphi again.
