### ISSUE TITLE
BufferPanel events has no effect

### ISSUE THREAD

**Issue by SoftacomDevelopment** [salvadordf/CEF4Delphi#254]
Win10x64, RAD Studio 10.3.2, CEF4Delphi 78.3.4
Demo app: Simple FMX Browser
FMXBufferPanelAdded to the form with browser (alighn: client, or placed with fixed height in bottom), canfocus := true; created eventhandlers like OnClick, OnMouseWheel.  Events dint fired up after mouse click over the panel or mouse wheel

**Comment by salvadordf** [comment]
Hi,

The SimpleFMXBrowser uses a TFMXChromium in _normal_ mode while the TFMXBufferPanel component is only used by TFMXChromium components in _OSR_ mode as you can see in the FMXExternalPumpBrowser demo.

Please, upgrade to the latest CEF4Delphi version which uses CEF 78.3.9 because if fixes several crashes. 

In general, the FMX demos are much more complicated. I would recommend to use the SimpleBrowser2 and SimpleOSRBrowser VCL demos for the first tests with CEF4Delphi. 

Please, use our forum for more questions :
https://www.briskbard.com/forum/

**Comment by SoftacomDevelopment** [comment]
Thanks a lot
