### ISSUE TITLE
Accessing DOM after load url

### ISSUE THREAD

**Issue by joweste** [salvadordf/CEF4Delphi#260]
Hi, 
After I load a url in chromium, I need to read some html elements.
Is there some event to indicate when the html document  was completelly loaded such as I can use a JS to read some html elements?

Regards,
Luiz

**Comment by salvadordf** [comment]
Hi,

It can be tricky to to detect when it's completely loaded because some pages add content dynamically.

You can use the TChromium.OnLoadingStateChange event but it's not 100% reliable.

Read this forum post for more details :
https://www.briskbard.com/forum/viewtopic.php?f=8&t=951&p=4213

Please, use our forums for more questions.
https://www.briskbard.com/forum/
