### ISSUE TITLE
Document.referrer doesn't work

### ISSUE THREAD

**Issue by kostyahohlov** [salvadordf/CEF4Delphi#27]
Hello, i'm trying to set custom HTTP-Referrer in my application. I tested it using (and expanding a little) the demo MiniBrowser.

To do that i wrote a function for event-handler OnBeforeResourceLoad.

procedure TWinRETestReferrerFrm.ChromeOnBeforeResourceLoad(Sender: TObject; const browser: ICefBrowser; const frame: ICefFrame; const request: ICefRequest; const callback: ICefRequestCallback; out Result: TCefReturnValue);
begin
  request.SetReferrer(String('http://mysite.com'), REFERRER_POLICY_ALWAYS);
end;

This code works and if i test my HTTP-Referrer header on some web-sites like https://www.whatismyreferer.com/ it displays me the correct referrer.

But i discovered a problem - it doesn't set corresponding referrer in "document.referrer" in Javascript. This way this referrer cannot be tracked by Google Analytics and some other trackers. To do the test i use method "LoadURL" like 

Chromium1.LoadURL(URLCbx.Text);

Is it possible to manage it from Delphi? Or do i need probably to configure something? Thank you by advance.

**Comment by salvadordf** [comment]
According to the official forum you can modify "document.referrer" indirectly by modifying the HTTP headers in the TChromium.OnBeforeResourceLoad event : 
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=11913

As far as I know, modifying request.SetReferrer should be enough.

Maybe some of the code in TChromium is messing with the headers. Try commenting these lines in uCEFChormium.

Inside TChromium.Internal_UpdatePreferences comment this line : 
UpdatePreference('enable_referrers',    FSendReferrer);  

Inside TChromium.doOnBeforeResourceLoad comment this line : 
if not(FSendReferrer) then request.SetReferrer('', REFERRER_POLICY_NEVER);

**Comment by kostyahohlov** [comment]
Hello, thank you for your advice. We tried it and discovered a strange behavior.

We use MiniBrowser-demo expanding it a little to do the tests.
We define our event-handler for OnBeforeResourceLoad event like this:

procedure TWinRETestReferrerFrm.ChromeOnBeforeResourceLoad(Sender: TObject; const browser: ICefBrowser; const frame: ICefFrame; const request: ICefRequest; const callback: ICefRequestCallback; out Result: TCefReturnValue);
begin
request.SetReferrer(String('http://mysite.com'), REFERRER_POLICY_ALWAYS);
end;

We tried also the same code in the the event-handler OnBeforeBrowse (because this one seems to be the very first). The same results as described below were get.

1. If the requested URL performs some 301 Redirect (for example if you request for http://noob-club.ru it did the redirect) then "document.referrer" is set well and also HTTP-header is set well . Else if it is some direct request without redirect (like http://www.noob-club.ru/index.php?topic=44899.0) then no HTTP-header Referer nor "document.referrer" is set.

2. We tried to use method LoadRequest like this:

var aRequest: ICefRequest;
      aHeader: ICefStringMultimap;

...


  aRequest := TCefRequestRef.New;


  aRequest.Url := 'http://somesite.com';
  aRequest.Method := 'GET';
  aRequest.Flags := [];

  aHeader := TCefStringMultimapOwn.Create;
  aRequest.SetHeaderMap(aHeader);
  aRequest.SetReferrer('http://mysite.com', REFERRER_POLICY_ALWAYS);

  Chromium1.Browser.MainFrame.LoadRequest(aRequest);

And this method works but strangely: this code is inside of button click handler, and it doesn't works in the first time. In the second time (when we click the second time) it works well always setting "document.referrer" and Referer HTTP-header. 

It looks like Request object is updated (or even replaced and Referer starts to work) by the new settings only in some circumstances: second time when we call LoadRequest OR always on 301 Redirect if we call LoadURL (and never with LoadURL if there are no Redirect). 

Do you have some ideas why it works like this? Probably we did something badly. Thank you by advance!

**Comment by salvadordf** [comment]
Please, use the forum for these questions :  
https://www.briskbard.com/forum/

The request in the OnBeforeBrowse event cannot be modified. These are the CEF3 source comments about that event in the /include/capi/cef_request_handler_capi.h file : 
`
  ///
  // Called on the UI thread before browser navigation. Return true (1) to
  // cancel the navigation or false (0) to allow the navigation to proceed. The
  // |request| object cannot be modified in this callback.
  // cef_load_handler_t::OnLoadingStateChange will be called twice in all cases.
  // If the navigation is allowed cef_load_handler_t::OnLoadStart and
  // cef_load_handler_t::OnLoadEnd will be called. If the navigation is canceled
  // cef_load_handler_t::OnLoadError will be called with an |errorCode| value of
  // ERR_ABORTED.
  ///
`
I've never used LoadRequest so I'm not sure if you're using it correctly.

I would try these things : 
- Have you loaded 'about:blank' before calling LoadRequest? Maybe the first time there was no valid "MainFrame".
- Have you tried to define the request variable in the pas unit instead of a local variable? Delphi releases all local interfaces when you exit that function.
- I'm not sure the current implementation of TCefRequestRef can be used in the LoadRequest function. I should look into the CEF3 sources but maybe you should use a TCefRequestOwn (which is not implemented in CEF4Delphi) to control when it is released.
