### ISSUE TITLE
how to use dark mode

### ISSUE THREAD

**Issue by bpeboulot** [salvadordf/CEF4Delphi#300]
is there an option or something to activate to use dark mode ?
I think my chromium browser dont receive or don't have access to Windows theme setup.
in my css I have the media prefers-color-scheme selection
`@media (prefers-color-scheme: dark) {
  body {
      background: #444;
      color: white;
  }
}
@media (prefers-color-scheme: light) {
    body {
        background-color: yellow;
    	color: #333;
    }
}
​`
if I test the media in javascript all is ok (I've got the alert)
`if (window.matchMedia('(prefers-color-scheme)').media == '(prefers-color-scheme)') {
    alert('🎉 Dark mode is supported');
}`
please help

**Comment by salvadordf** [comment]
I tried several switches from this thread : 
https://bugs.chromium.org/p/chromium/issues/detail?id=889087

...but none of them seem to work with the official CEF sample application on Windows 10 with the dark mode selected in the OS.

I would suggest that you ask in the CEF project forum : 
https://magpcss.org/ceforum/

I'll keep looking for more information because I'm also interested in tis feature.

**Comment by EricGrange** [comment]
There is an open issue in CEF repo, I just annotated it with a reference to Electron's similar issue (and potential fix)

https://bitbucket.org/chromiumembedded/cef/issues/2824/support-prefers-color-scheme-media-query

**Comment by salvadordf** [comment]
There's a new CEF commit that adds support for prefers-color-scheme media queries but we'll have to wait until CEF 86 because it's not in the current stable branch.
https://bitbucket.org/chromiumembedded/cef/commits/37c9e4cdf87c12c70d05fa9dd7272ec66b520846

**Comment by salvadordf** [comment]
And this is the release schedule : 
https://chromiumdash.appspot.com/schedule

**Comment by salvadordf** [comment]
The latest CEF binaries fixed this issue. Please, update to the latest CEF4Delphi version.
