### ISSUE TITLE
Access violation in libcef.dll when closing ExternalPumpBrowser.exe --single-process

### ISSUE THREAD

**Issue by mterrisse** [salvadordf/CEF4Delphi#306]
Hello,

I compiled demos\Delphi_VCL\ExternalPumpBrowser\ExternalPumpBrowser.dproj and ran it under Delphi with the command ligne --single-process.
When I close the application, there is an access violation in libcef.dll in the main thread during the call of cef_shutdown (TCefApplicationCore.ShutDown).
I suppose something is missing before the call of cef_shutdown.

Regards,

Michel Terrisse

**Comment by salvadordf** [comment]
The single process mode is not supported by CEF and it's only for debugging purposes. 
This is the same issue as #291 
https://github.com/salvadordf/CEF4Delphi/issues/291

**Comment by mterrisse** [comment]
Indeed I read that it is supported only for debugging purposes (even thow I don't know why).
I need --single-process because of this bug in CEF
  https://bitbucket.org/chromiumembedded/cef/issues/3028/cefclientexe-doesnt-work-on-wine-on-macos

Do you think I should report this shutdown problem as an issue in CEF instead of CEF4Delphi?

Regards,

Michel Terrisse

**Comment by salvadordf** [comment]
This is what Chromium's documents say about that mode : 
http://www.chromium.org/developers/design-documents/process-models
"_The single process model provides a baseline for measuring any overhead that the multi-process architectures impose. It is not a safe or robust architecture, as any renderer crash will cause the loss of the entire browser process. It is designed for testing and development purposes, and it may contain bugs that are not present in the other architectures._"

That shutdown crash is a CEF4Delphi issue in the single process mode. I will try to fix that crash even if that mode is not supported because cefclient doesn't crash in that situation.

However, I would not recomend releasing applications using that mode because you **will** have unexpected issues.

**Comment by mterrisse** [comment]
I just realized that
  cefclient.exe --external-message-pump --single-process
doesn't crash, but probably because the exception is catched.
If I run
  lldb cefclient.exe -- --external-message-pump --single-process
I can see that there is an access violation.
So I will report this as a CEF issue.
Thank you for your help.

Michel Terrisse
