### ISSUE TITLE
Write permission denied

### ISSUE THREAD

**Issue by yesilcimenahmet** [salvadordf/CEF4Delphi#326]
Hi,

I am using below lines in Normal Chrome Browser.

```
 var prop = Object.defineProperty({}, blob.type, {
      value: blob,
      enumerable: true
});
item = new ClipboardItem(prop);
navigator.clip
blob is image.board.write([item]);
```

It works great in the browser, but does not work in the Delphi application either.
 the error I got is this: **Uncaught (in promise) DOMException: Write permission denied.**

I am using below options for Global settings.

>   GlobalCEFApp.WindowlessRenderingEnabled := True;
>   GlobalCEFApp.DisableWebSecurity := True;
>   GlobalCEFApp.DisableSafeBrowsing := True;
>   GlobalCEFApp.EnableHighDPISupport := True;
>   GlobalCEFApp.EnableGPU := True;

Please help how can i fix this?

Thanks.

**Comment by salvadordf** [comment]
I'm sorry but this is probably caused by the same problem you described here : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=1410&p=5864

At this moment CEF doesn't implement that API but it seems that the new feature request called "Support chrome windows with CEF callbacks" will add support for that.
https://bitbucket.org/chromiumembedded/cef/issues/2969/support-chrome-windows-with-cef-callbacks

**Comment by yesilcimenahmet** [comment]
Thank you. I hope you include them when this support comes in.
