### ISSUE TITLE
Alert max message length changes from CEF3 to CEF4 ?

### ISSUE THREAD

**Issue by PlanetIrata** [salvadordf/CEF4Delphi#327]
Hi, I'm using `alert` to communicate from javascript with my Delphi app. This works like a charm since CEF3, but I experience issues with CEF4 with very long messages, it seems that they are truncated above approximately 10.000 characters, which was not the case in CEF3.

Can you confirm this and is there a way to configure the maximum lengh of dialog messages ?

Thanks!

**Comment by salvadordf** [comment]
Delphi strings have a much bigger limit than 10.000 chars so if you reached that limit it means that it's caused by something else. Most probably by the new Chromium version used by CEF4Delphi.

Register a JavaScript extension to send information to the main browser process or use a custom IPC message, perhaps using websockets.

**Comment by PlanetIrata** [comment]
Thanks! Yes it is on the Chromium side that the string ius truncated. Could you point me to some demos that show how to use a JS extension or websockets ? What is the simplest and most reliable way to send back to the Delphi a **string** (sometimes a long one) from CEF ?

**Comment by salvadordf** [comment]
I forgot to tell that you can also try the "_console trick_" to send information to the main browser process. Read the code comments in the DOMVisitor demo to know more details about that trick because it's the easiest way to send information.

Take a look at the JSExtension and JSRTTIExtension demos inside the "demos\JavaScript" directory for more details about JavaScript extensions. Read the code comments in JSExtension.

**Comment by PlanetIrata** [comment]
Thx, but it seems that the *"console trick"* is limited also to 10K characters messages:

```pascal
// This method for sending text messages is limited to around 10000 characters
// but it's much easier to implement than using a JavaScript extension.
```

A thread on the forum ([Re: Return function JavaScrit in Delphi](https://www.briskbard.com/forum/viewtopic.php?t=1251#p5324)) says that `prompt` may work for messages up to 200K characters. 

Will test that

Maybe It could be useful to add these limits in the main documentation ?

**Comment by salvadordf** [comment]
You're right. I'll add that information to the docs or code comments.

**Comment by PlanetIrata** [comment]
@salvadordf Thanks, the limit seems to be 10240 characters with `alert`, but the default value for the `prompt` command works up to 200MB (for now).
