### ISSUE TITLE
FPC compatibility

### ISSUE THREAD

**Issue by JulStrat** [salvadordf/CEF4Delphi#331]
Good day, Salvador!

One question  - why do you use  {$MODE OBJFPC} ?
I think the only right mode for Delphi / FPC compatibility is {$MODE Delphi}.
Also, don't forget about compiler directive {$PACKRECORDS C}, if you use C bindings (dynamic libraries).
I can prepare patch / PR if you wish.

My best regards and Happy New Year!

Julian.

**Comment by salvadordf** [comment]
Hi,

The OBJFPC mode was added when I added Lazarus/FPC support in CEF4Delphi. 

As you know, CEF4Delphi is based in DCEF3 and at that moment CEF4Delphi only supported Delphi. 

The fpCEF3 project was similar to DCEF3 and it worked on Lazarus so I compared the code of those 2 projects and adapted the differences to CEF4Delphi.

fpCEF3 used the OBJFPC mode and it was much easier to keep using it.

The PACKRECORDS is not used by DCEF3 or fpCEF3. I'll keep it in mind when I try to fix the issue #278 because it could be the solution.

Thank you very much and happy new year! :D
