### ISSUE TITLE
windows-32bit- when start by another program went wrong

### ISSUE THREAD

**Issue by loveacat** [salvadordf/CEF4Delphi#338]
hi , sorry for my poor english, i write a 32bit delphi program and use 32 bit cef, it all went ok. but my program has to be embed into a 64 bit application. when this application run  and start my program , it toast error , wrong cef binaries,use the 64 bit cef binaries with the 64 bit application. what shoud i do ? recomplie the program use the 64bit cef ?

**Comment by salvadordf** [comment]
It depends on how you embed those programs but it would be easier if all the projects were compiled in 64 bits.

- If the 64 bit project is reusing parts of the 32 bits project like frames, forms, etc. then you should use the 64 bits CEF binaries.
- If the 64 bit application just runs the main *.exe of the 32 bits application then it should use the 32 bits binaries. Notice that I mentioned the **main** *.exe because if the 64 bits application is trying to use the 32 bits *.exe for the CEF subprocesses then you will have to build everything in 64 bits and use the 64 bits CEF binaries.

Please, use our forums for more questions : 
https://www.briskbard.com/forum/
