### ISSUE TITLE
How create browser hands ?

### ISSUE THREAD

**Issue by Uefi1** [salvadordf/CEF4Delphi#375]
CEFWindowParent1 does not display anything, are memo1.Lines.Add(chrom.Browser.MainFrame.Url); - error Access Violation 

procedure TForm1.Button1Click(Sender: TObject);
var
chrom:tchromium;
begin
chrom:=tchromium.Create(self);
Chrom.CreateBrowser(CEFWindowParent1, 'self');
Chrom.Initialized;
chrom.LoadURL('https://yandex.ru')
//memo1.Lines.Add(chrom.Browser.MainFrame.Url);
end;
Help please

**Comment by salvadordf** [comment]
Hi,

Some procedures and methods in TChromium are asynchronous and return immediately. 
When you use the default settings TChromium.CreateBrowser is asynchronous and it returns before the browser is initialized.

Use the SimpleBrowser2 demo as a template for your application. 

If possible, use the TChromium procedures and methods instead of accessing internal CEF interfaces like TChromium.Browser.MainFrame.Url because TChromium checks that the browser is fully initialized and validates the CEF interfaces before using them. 

Please, use our forum for more questions : 
https://www.briskbard.com/forum/

**Comment by Uefi1** [comment]
How i can do this ?
