### ISSUE TITLE
CEF4Delphi Cannot run on Windows XP

### ISSUE THREAD

**Issue by cgs0** [salvadordf/CEF4Delphi#38]
I wrote an application and sent it to user .
I got an error on open app in Windows XP
Error meesage  likes
Cannot find QueryUnbiasedInterruptTime on Kernel32.dll

![errorxp](https://user-images.githubusercontent.com/26734016/27812042-75c48828-609e-11e7-9fb8-b014c55f370a.jpg)

I check Windows XP , it don't have the function on kernel32 .

**Comment by salvadordf** [comment]
Google announced that they would drop Windows XP support for Chrome in 2015. 

Chrome version 50 was no longer compatible with Windows XP and the last CEF3 branch that was compatible with Windows XP was 2623. 

If you need Windows XP compatibility you have to use the 2623 branch of DCEF3.
https://github.com/hgourvest/dcef3/tree/2623

Since CEF4Delphi uses the 3071 branch, it's **not** compatible with Windows XP, Windows Vista, Windows Server 2003 and Windows Server 2008.
