### ISSUE TITLE
How to open encrypted pdf files sending password through delphi?

### ISSUE THREAD

**Issue by claudioprv** [salvadordf/CEF4Delphi#385]
Hi developer,
First, congratulations on developing this component.
I would like to know if it is possible for me to open a PDF document encrypted with password passing the password in run-time, without the need for the user to type the password.
Example: The user will open the PDF file with password but he cannot know the password, I will pass the password through Delphi, so I would avoid opening the box to enter the password.

Something like Chromium1.LoadURL(url, pdfpassword);
or some pdf.password property

Thank you in advance,
Cláudio.

**Comment by salvadordf** [comment]
CEF doesn't expose any event to automate typing the password in a PDF file.
The current authentication events are triggered for protected network resources and the passwords in PDF files don't fall into that category.
I searched for command line switches related to this and all I could find was ways to disable the internal PDF reader in Chromium.
I also tried to include a password in the FILE URI and it didn't work.

If you know which files are encrypted with a password then you might be able to send key presses with the password to the browser in order to automate this process.

If you can't anticipate which files may ask for a password then you would have to modify Chromium's source or use an alternative PDF reader component.
