### ISSUE TITLE
After onBeforeClose timeout

### ISSUE THREAD

**Issue by Curtyop** [salvadordf/CEF4Delphi#389]
Thank you so much for the development. There was another question. A memory access error occurs. 
procedure TCEFBrowserWrap.Browser_OnBeforeClose(Sender: TObject; const browser: ICefBrowser);
begin
 FCloseBrowserEvent.SetEvent;
end;

function TCEFBrowserWrap.CloseBrowser:boolean;
begin
  result:=false;
  if not(FClosing) and assigned(FChromium) then begin
    FClosing := True;
    FCloseBrowserEvent.ResetEvent;
    try
     FChromium.CloseBrowser(true);
     if WaitForCloseBrowserEvent(60000) then result:=true;
    finally
//     sleep(1000);// For some sites one second delay is not enough and memory access error occurs 
     sleep(2000);
    end;
  end;
end;

destructor TCEFBrowserWrap.Destroy;
begin
  if (FChromium <> nil) then  FreeAndNil(FChromium);
  if (FPanel <> nil) then  FreeAndNil(FPanel);
  if (FPopUpBitmap <> nil) then FreeAndNil(FPopUpBitmap);
  if (FSnapshot <> nil) then FreeAndNil(FSnapshot);
  if (FResizeCS <> nil) then FreeAndNil(FResizeCS);
  if (FBrowserInfoCS <> nil) then FreeAndNil(FBrowserInfoCS);
  if (FCloseBrowserEvent <> nil) then FreeAndNil(FCloseBrowserEvent);

  inherited Destroy;
end;

.......
CEFBrowserWrap:=TCEFBrowserWrap.Create(...);
CEFBrowserWrap.CloseBrowser;
freeandnil(CEFBrowserWrap);

Most likely it appears in the subprocess due to unfinished events (this is my guess). How to understand exactly that TChromium can be destroyed? Because there may be sites where you will need to wait more than two seconds.

**Comment by salvadordf** [comment]
Using events to close a browser is very tricky and it's only used in the ConsoleBrowser2 demo. 

That demo handles the browser in a thread called TCEFBrowserThread to avoid problems because the main application thread is blocked waiting for the event.

You can use the code in the ConsoleBrowser2 demo in your app but it's recommended to use the traditional destruction steps described in the code comments of every demo.

Please, use our forum for more questions :
https://www.briskbard.com/forum/
