### ISSUE TITLE
ICefv8Value.SetUserData() (and GetUserData())

### ISSUE THREAD

**Issue by uniho** [salvadordf/CEF4Delphi#394]
Can you change argument of ICefv8Value.SetUserData() and SetUserData() from ICefv8Value to ICefBaseRefCounted as [CEF C++ API](https://magpcss.org/ceforum/apidocs3/projects/(default)/CefV8Value.html#SetUserData(CefRefPtr%3CCefBaseRefCounted%3E))?

**Comment by salvadordf** [comment]
Hi,

You're right. The right argument data type for ICefv8Value.SetUserData() and ICefv8Value.GetUserData() should be ICefBaseRefCounted instead of ICefv8Value.

However, CEF has a very unique way to handle interfaces that breaks the Delphi definition of interface inheritance.

If we use ICefBaseRefCounted for SetUserData and GetUserData then we can't use "_SysUtils.supports_", "_IInterface.QueryInterface_" or "_as_" to get the right interface reference that we originally used with SetUserData.

Consider converting your user data to any of the supported data types that ICefv8Value can handle or try using an alternative method to pass that information.

**Comment by uniho** [comment]
Thanks for your quick reply!
You mean we cannot know GC timing from native code like [this thread](https://magpcss.org/ceforum/viewtopic.php?f=10&t=11027) says?

**Comment by salvadordf** [comment]
If you really need to know that then you can modify the ICefv8Value interface and the TCefv8ValueRef class declarations. 

Set the data type for ICefv8Value.SetUserData() and ICefv8Value.GetUserData() with your own custom ICefBaseRefCounted descendant and send a message when the instance of that custom class is destroyed.

You will also have to remove the TCefRTTIExtension class because it uses ICefv8Value.SetUserData() and ICefv8Value.GetUserData() with the current data type.

**Comment by uniho** [comment]
Yeah, I want to create TProcess Object (I'm using Lazarus) on TTask thread using JS Promise, to read stdin and stderr from pipe, and kill it on GC timing.
I will try.
It is kind of you!

**Comment by salvadordf** [comment]
I just remembered that you could also use the current ICefv8Value.SetUserData() and ICefv8Value.GetUserData() implementation and use TCefv8ValueRef.NewArrayBuffer to create a fake array with a user defined destruction callback function.

That callback will be called when the GC needs to destroy that array and you could also add extra code to send a message to the main browser process with your information.

**Comment by uniho** [comment]
Hi, [new project launched](https://github.com/uniho/BeBop)!
Thanks for your advice!
