### ISSUE TITLE
Error compiling CEF4Delphi package for Lazarus

### ISSUE THREAD

**Issue by Yogerlan** [salvadordf/CEF4Delphi#395]
uCEFBufferPanel.pas(494,11) Error: identifier idents no member "ForceQueue"

CEF4Delphi: 95.0.4638.69
OS: Linux Mint 20.1 Ulyssa
Lazarus: 2.0.6+dfsg-3
fpc: 3.0.4+dfsg-23

Any help will be appreciated.

**Comment by salvadordf** [comment]
That error is probably caused by the version of Lazarus and FPC.

I just built several Linux demos without problems using this configuration : 

- The latest CEF4Delphi version : Updated to CEF 96.0.16 which includes Chromium 96.0.4664.55.
- Linux Mint 20.2 Cinnamon
- Lazarus 2.2RC2
- FPC 3.2.2

Try updating to the latest Lazarus/FPC versions available here : 
https://sourceforge.net/projects/lazarus/files/
