### ISSUE TITLE
Remember username and password

### ISSUE THREAD

**Issue by fraurino** [salvadordf/CEF4Delphi#400]
how to make the browser remember the username and password when accessing a website, just like chrome?

**Comment by salvadordf** [comment]
Hi,

If you mean that you need to keep the sessions open then you need to set a writable directory for the browser cache.

However, if you meant that you need to store the login credentials to fill forms then you have to implement it from scratch because CEF doesn't include that.

Please, use our forums for more questions : 
https://www.briskbard.com/forum/
