### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by Alexeich7** [salvadordf/CEF4Delphi#404]
Setting `ChromiumMain.DefaultUrl := '';`  in FormCreate and no LoadURL called causes memory leakage when app is closed.
Leaks TCustomRequestContextHandler x1, Unknown x1.

**Comment by salvadordf** [comment]
The DefaultURL property is used as a parameter when TChromiumCore creates the browser and the default value of that property is _about:blank_.

All the official CEF sample applications always use a valid URL when they create a browser.

Perhaps Chromium is not expecting that we use an empty URL to create a browser and that's why the TCustomRequestContextHandler copy that is passed to Chromium is never released.

I'll modify TChromiumCore to use _about:blank_ if DefaultURL is empty.
