### ISSUE TITLE
Instalation in Delphi 10

### ISSUE THREAD

**Issue by Bogmajster** [salvadordf/CEF4Delphi#418]
When i try install package CEF4Delphi_designtime  i get message 
Delphi 10
CEF 101.0.15

Registration procedure, Cef4delphivclfmx_register.Register in package 
C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl\CEF4Delphi_designtime.bpl 
raised exception class EAccessViolation: Access violation at address 5005FC08 in module 'rtl230.bpl'. Read of address FFFFFFD0.

**Comment by a-nouri** [comment]
I got sam error in delphi 11.1
I will check updated installation in delphi now.
thanks

**Comment by salvadordf** [comment]
This issue should be fixed with the updated installation instructions in the Wiki. 

In case this issues appears again please make sure you deleted all BPL and DCU files from old CEF4Delphi installations. If you keep several CEF4Delphi versions in your computer then check that CEF4Delphi is not included in the Delphi _Library path_ or the _PATH_ environment variable.
