### ISSUE TITLE
Android or iOS

### ISSUE THREAD

**Issue by VTwo-Group** [salvadordf/CEF4Delphi#429]
Is it possible to use Chromium in Android or iOS in the future with cef?

**Comment by salvadordf** [comment]
Read [this issue](https://github.com/salvadordf/CEF4Delphi/issues/407) and the liked CEF issue to know the current status of the Android support. 

Vote for that issue at Bitbucket if you want to accelerate its development.

About iOS, the CEF project maintainer said that it's highly unlikely due to Apple restrictions. Read the full forum thread [here](https://magpcss.org/ceforum/viewtopic.php?t=10877).
