### ISSUE TITLE
SetUserAgentOverride makes Client Hints null

### ISSUE THREAD

**Issue by Gurkan-Aktas** [salvadordf/CEF4Delphi#434]
For a project we need to set User Agent, however method below causes all Client Hints to be null.
procedure TChromiumCore.SetUserAgentOverride(const aUserAgent, aAcceptLanguage, aPlatform : ustring);

Please recommend a way to set Client Hints later, or prevent setting UserAgent damaging Client Hints.

Tried setting platform value to Windows by updating Sec-Ch-Ua-Platform header, with below code :
request.SetHeaderByName('Sec-Ch-Ua-Platform', 'Windows', true);
at OnBeforeResourceLoad event
however did not work (it works for some headers, some seem special and not affected, does not work for those starting with Sec-Ch).

Please help..

**Comment by salvadordf** [comment]
Hi,

Sec-CH-UA Client Hints seem to be unsupported by CEF. Read [this CEF issue.](https://bitbucket.org/chromiumembedded/cef/issues/3136/cef-89-alloy-support-feature-sec-ch-ua) 

TChromiumCore.SetUserAgentOverride uses the [Emulation.setUserAgentOverride](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setUserAgentOverride) DevTools method.

Possible workaround 1 : 
Try setting the GlobalCEFApp.UserAgent property before the GlobalCEFApp.StarMainProcess call in the DPR file.

Possible workaround 2 : 
Build the CEF binaries after applying the code in [PR #372](https://bitbucket.org/chromiumembedded/cef/pull-requests/372/support-feature-sec-ch-ua-client-hints)  

Possible workaround 3 : 
You can also try the new and **experimental** "_Chrome runtime_" mode. In order to try this mode in the MiniBrowser demo set GlobalCEFApp.ChromeRuntime := True; [here](https://github.com/salvadordf/CEF4Delphi/blob/466f40916d9273862dc6ef11b7da223c69831b6a/demos/Delphi_VCL/MiniBrowser/uMiniBrowser.pas#L321) 

In any case, this is a CEF feature that needs to be implemented. I would suggest that you ask about the status of this feature in [this CEF issue](https://bitbucket.org/chromiumembedded/cef/issues/3136/cef-89-alloy-support-feature-sec-ch-ua).

Please, use [our forums](https://www.briskbard.com/forum/) for more questions.
