### ISSUE TITLE
Error: Cold not find GetProcessMitigationPolicy

### ISSUE THREAD

**Issue by tebosoftware** [salvadordf/CEF4Delphi#452]
Good morning

I'm building a browser and testing the MiniBrowser demo, with all the dlls and dependencies in the executable folder, I'm getting the error:
`"Could not find procedure entry point GetProcessMitigationPolicy in interactive link library KERNEL32.dll. "`
I'm testing inside windows 7 professional SP1 and Delphi 10

**Comment by tebosoftware** [comment]
I discovery that chromium is not compatible with windows 7.

**Comment by salvadordf** [comment]
If you're using the latest CEF4Delphi version which includes Chromium 110 then this issue could be caused by the [new operating system requirements that Google added to Chromium](https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-1-in-early-2023?hl=en).

This means that Windows 7, 8/8.1, Windows Server 2012, and Windows Server 2012 R2 are not supported by Chromium 110.

If you need to support Windows 7 then use [this CEF4Delphi release](https://github.com/salvadordf/CEF4Delphi/releases/tag/109.0.5414.120).
