### ISSUE TITLE
CEF initialization is very slow, with a wait time of more than 5 minutes

### ISSUE THREAD

**Issue by babyluoyi** [salvadordf/CEF4Delphi#460]
Sometimes CEF initialization is not completed for more than 5 minutes. After closing, reopen the program, and it can run normally again, how to solve it?
--------------------
windows 7 32bit.
CPU：Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz 3.40 GHz
Memory：16G
libcef.dll：97.1.1.0
--------------------
<img width="1276" alt="image" src="https://github.com/salvadordf/CEF4Delphi/assets/23548657/f9d7ace5-0e0b-4cb8-a806-118d7abccddc">

**Comment by salvadordf** [comment]
Hi,

This issue might be caused by some initialization code in other units. If your application has a complicated initialization try using a different EXE for the CEF subprocesses. See the [SubProcess](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/Delphi_VCL/SubProcess) demo for all the details.

Read [this forum thread](https://www.briskbard.com/forum/viewtopic.php?f=10&t=2077) for a similar problem with the same solution.

Please, use [our forum](https://www.briskbard.com/forum/index.php) for more questions.
