### ISSUE TITLE
32 bit arm linux binaries are not available please 

### ISSUE THREAD

**Issue by cslattery117** [salvadordf/CEF4Delphi#465]
https://cef-builds.spotifycdn.com/cef_binary_112.3.0%2Bgb09c4ca%2Bchromium-112.0.5615.165_linuxarm.tar.bz2

gives a page not found error .... can anyone help thanks

**Comment by salvadordf** [comment]
It seems that the automated build system stopped creating the binaries for Linux ARM 32 bit after CEF 111.2.7
Try using [this CEF4Delphi release](https://github.com/salvadordf/CEF4Delphi/releases/tag/106.0.5249.119) in order to avoid some GTK2 issues.
If you still want to use the CEF 112 binaries then post your question in the [official CEF forum](https://magpcss.org/ceforum/).
