### ISSUE TITLE
HTML displays in browser but not in CEF

### ISSUE THREAD

**Issue by mjsouza1977** [salvadordf/CEF4Delphi#475]
I use the CEF to display a google map and suddenly overnight the map is simply not displayed, until the system returns to previous versions.

Here is the link to the file we are having problems with:
https://drive.google.com/file/d/1xaLWndd6pdnDIYdgcGbINkA2WxvC9Jku/view?usp=sharing

**Comment by salvadordf** [comment]
Hi,

Use the DevTools in a CEF browser and read the messages in the Console tab. Those message may have clues about this issue.
 
It seems that you are trying to use the Google Maps API. See the Google console error messages to know more details about this issue.

This issue is outside the scope of CEF4Delphi but feel free to write about it in [our forum](https://www.briskbard.com/forum/).
