### ISSUE TITLE
Regarding the issue of extension loading, HelloWorldExt and PageColorExt

### ISSUE THREAD

**Issue by sxmxta** [salvadordf/CEF4Delphi#507]
hello
I changed the HelloWorldExt and PageColorExt examples to Lazarus and they won't work properly

The load extension button can be used normally
There is no response after clicking the pop-up extension button

**Comment by salvadordf** [comment]
Hi,

According to the [CEF project maintainer](https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=19543#p54033) `Alloy support for extensions has not been specifically removed. However, it is untested/unsupported for anything other than PDF Viewer and Print Preview.` 

He [recently added](https://github.com/chromiumembedded/cef/issues/3654#issuecomment-1961604386) that `You can use extensions with the Chrome runtime`

The HelloWorldExt and PageColorExt demos are old examples and I should remove them because they stopped working in recent CEF versions.

Read [this issue](https://github.com/chromiumembedded/cef/issues/3681) about the future of the _alloy_ and _chrome runtime_ modes in CEF.
