### ISSUE TITLE
uMiniBrowser.pas(139,23) Error: Identifier not found "ICefMediaAccessCallback"

### ISSUE THREAD

**Issue by panjunqiao** [salvadordf/CEF4Delphi#522]
![企业微信截图_20240626181232](https://github.com/salvadordf/CEF4Delphi/assets/8489040/23170839-1c80-4d50-be95-59d26770411c)

**Comment by salvadordf** [comment]
Hi,

Open the cef4delphi_lazarus.lpk package, build it and install it.

After that Lazarus will restart and then open the MiniBrowser demo found in CEF4Delphi\demos\Lazarus_Windows\MiniBrowser

That project requires the CEF4Delphi_Lazarus package and it should find ICefMediaAccessCallback because it's available in the uCEFInterfaces unit.

**Comment by panjunqiao** [comment]
I have successfully run it, thank you very much!
