### ISSUE TITLE
Can you provide a Cef4Delphi that supports Windows 7, 8, 10, and above versions?

### ISSUE THREAD

**Issue by mytvdat** [salvadordf/CEF4Delphi#530]
cef4delphi for windows7 has many bugs, it cannot play videos, and the new version does not support Windows 7

**Comment by salvadordf** [comment]
Due to licensing issues and the US patent law, the CEF binaries available at Spotify have the proprietary codecs disabled. If you use those binaries, any website that offers media using H264 won't work.

[Google announced](https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-1-in-early-2023?hl=en) that Chromium would not support Windows 7, 8.0 or 8.1 in 2022. 

The last version of CEF with Windows 7 support was CEF 109 and [this is the last CEF4Delphi release](https://github.com/salvadordf/CEF4Delphi/releases/tag/109.0.5414.120) with Windows 7 support.

Read [this document](https://www.briskbard.com/index.php?lang=en&pageid=cef) for more information.

**Comment by mytvdat** [comment]
Chromium v94 support Windows 7, 8.0 or 10,but it can play all videos. my windows uses Chromium v94 ,it works well,not any bugs.
CEF 109 support Windows 7,but it can not play all videos.it crashes at closing application.
