### ISSUE TITLE
JavascriptOpenWindows missing

### ISSUE THREAD

**Issue by petko** [salvadordf/CEF4Delphi#54]
I see that the `JavascriptOpenWindows` option was removed in July. What is the reason and what is the default state of this property now?

**Comment by salvadordf** [comment]
The CEF3 commit that removed that option is this : 
https://bitbucket.org/chromiumembedded/cef/commits/5c79944b316d85e43c89dfb732f16ac370900610?at=3163#chg-include/internal/cef_types.h

The comments say this : 

> Remove CefBrowserSettings.javascript_open_windows which is no longer supported.

That commit upgraded Chromium to the major version 61 and the javascript_open_windows change was probably due to that version change. I don't know its default state now but you can ask in the official CEF3 forum.
http://magpcss.org/ceforum/
