### ISSUE TITLE
Please... Make example for dll

### ISSUE THREAD

**Issue by h2285409** [salvadordf/CEF4Delphi#61]
Please... Make example for dll

GlobalCEFApp???

**Comment by salvadordf** [comment]
There are 16 demos for normal applications. If you need to create an ActiveX DLL I can't help you because I've never created that kind of components.

However, another github user called ashumkin added several changes to CEF4Delphi to make it easier to create ActiveX DLLs.

Please read this web page for more information about GlobalCEFApp :
https://www.briskbard.com/index.php?lang=en&pageid=cef
