### ISSUE TITLE
How to register an extension?

### ISSUE THREAD

**Issue by raelb** [salvadordf/CEF4Delphi#7]
I have adapted the guiclient demo from DCEF3 to use CEF4Delphi. Once the components are replaced, most of the code works as is. 

I would like to use the code that registers a custom extension. However I was not sure how to adapt the code from the initialization section:

> initialization
  CefRemoteDebuggingPort := 9000;
  CefRenderProcessHandler := TCustomRenderProcessHandler.Create;
  CefBrowserProcessHandler := TCefBrowserProcessHandlerOwn.Create;
end.

[guiclient.zip](https://github.com/salvadordf/CEF4Delphi/files/765276/guiclient.zip)

**Comment by salvadordf** [comment]
CefRemoteDebuggingPort is now a property of TCefApplication called RemoteDebuggingPort. You can set it before the StartMainProcess call.

CefRenderProcessHandler and CefBrowserProcessHandler can only be set inside the TCefApplication.CreateInternalApp function because you must set them as properties of TInternalApp. 
The properties you should modify are TInternalApp.RenderProcessHandler and TInternalApp.BrowserProcessHandler

I'll take a deeper look this weekend.
