### ISSUE TITLE
MultiThreadedMessageLoop := False is now broken

### ISSUE THREAD

**Issue by petko** [salvadordf/CEF4Delphi#78]
I use   GlobalCEFApp.MultiThreadedMessageLoop := False in my project, because of some UI issues with third-party components. However, now by upgrading from 3.3163.1671 to 3.3202.1694, this option no longer works. The TChromium is never initialized.

Do you know what this happens or should I try finding the exact changeset that broke it?

**Comment by salvadordf** [comment]
I recently added 3 new demos to show how to use that mode : "ExternalPumpBrowser", "SimpleExternalPumpBrowser" and "OSRExternalPumpBrowser".

If you need to set GlobalCEFApp.MultiThreadedMessageLoop to False, It's also recommended to set GlobalCEFApp.ExternalMessagePump to True to schedule the cef_do_message_loop_work calls with the GlobalCEFApp.OnScheduleMessagePumpWork event.

I created the TCEFWorkScheduler class to handle the cef_do_message_loop_work calls.

Please download the latest CEF4Delphi and read this forum thread for more info : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=222

**Comment by petko** [comment]
In your demo you recommend a specific closing sequence for the browser, which includes the Form.OnClose event. Since I create my browsers in TFrame, which does not have the InClose event, instead of in TForm, should I some similar closing sequence or a simple TFrame.Destroy is sufficient?

**Comment by salvadordf** [comment]
Sorry for the delayed answer. I've never used frames. I'll try to make a new demo with them as soon as I can.

**Comment by salvadordf** [comment]
I just read a few web pages about TFrames and I'll try to explain how it should be destroyed instead of creating a new component just for a demo. 

Assuming you have only one TChromium in every TFrame, and several TFrames in your main form, you should follow almost the same destruction sequence used in the MDIBrowser demo.

If you have created several child forms in the MDIBrowser demo and you try to close the application, the main form will set CanClose to False in the OnCloseQuery event and wait until all the child forms are closed before closing the app.

In your case, you should set CanClose to False in the MainForm.OnCloseQuery event and wait until all the frames have destroyed their browsers before closing the app.

Your frames should handle the TChromium destruction sequence internally as described in the uChildForm.pas file but instead of sending a final WM_CLOSE, you can send a message to your main form to indicate that a frame is ready to be destroyed.

It doesn't matter if your frames don't have the same events than a TForm. You only need to use the OnCloseQuery in your main form and call TChromium.CloseBrowser inside every child frame to initiate the browser destruction sequence and wait until all frames have executed the TChromium.OnBeforeClose event. Then you can close the main form safely.
